var MSG = {
  title: "Rupai Bangla",
  blocks: "Blocks Bangla",
  openTooltip: 'Open file Bangla',
  saveTooltip: 'Save workspace as file Bangla',
  linkTooltip: "Save and link to blocks. Bangla",
  runTooltip: "Run the program defined by the blocks in the workspace. Bangla",
  badCode: "Program error:\n%1 Bangla",
  timeout: "Maximum execution iterations exceeded. Bangla",
  trashTooltip: "Discard all blocks. Bangla",
  catLogic: "Logic Bangla",
  catLoops: "Loops Bangla",
  catMath: "Math Bangla",
  catText: "Text Bangla",
  catLists: "Lists Bangla",
  catColour: "Colour Bangla",
  catVariables: "Variables Bangla",
  catFunctions: "Functions Bangla",
  listVariable: "list Bangla",
  textVariable: "text Bangla",
  httpRequestError: "There was a problem with the request. Bangla",
  linkAlert: "Share your blocks with this link:\n\n%1 Bangla",
  hashError: "Sorry, '%1' doesn't correspond with any saved program. Bangla",
  xmlError: "Could not load your saved file. Perhaps it was created with a different version of Blockly? Bangla",
  badXml: "Error parsing XML:\n%1\n\nSelect 'OK' to abandon your changes or 'Cancel' to further edit the XML Bangla"
};
