var MSG = {
  title: "ভিজুয়াল প্রোগ্রামিং এডিটর",

  tab_blocks: "ব্লকগুলি",
  tab_camera: "ফিড",
  tab_code: "কোড",

  aboutBtn:"রুপাই সম্পর্কে",
  exampleBtn:"উদাহরণ",
  helpBtn:"সাহায্য",


  openTooltip: 'ফাইল ওপেন করতে',
  saveTooltip: 'কোড ফাইলে সেভ করতে',
  linkTooltip: "Save and link to blocks.",
  runTooltip: "কোড রান করতে",
  trashTooltip: "সব কোড ডিলিট করতে",

  badCode: "Program error:\n%1",
  timeout: "Maximum execution iterations exceeded.",


  catAction: "অ্যাকশন",
  catControl: "কন্ট্রোল",
  catLogic: "লজিক",
  catMath: "গনিত",
  catText: "বাক্য",
  catLists: "লিস্ট",
  catSensors: "সেন্সর",
  catEvents: "ইভেন্ট",
  catDisplay: "ডিসপ্লে",
  catVariables: "চলক",
  catFunctions: "ফাংশন",
  listVariable: "লিস্ট",
  textVariable: "বাক্য",

    block : {
        goForwards: "সামনে যাও",
        goBackwards: "পিছনে যাও",
        goSteps: "ধাপ",
        stop: "থামো",
        turnLeft: "বামে বাঁক নাও",
        turnRight: "ডানে বাঁক নাও",
        eventVoice: "যখন ভয়েস ইনপুট",
        eventLeft: "যখন বাম",
        eventRight: "যখন ডান",
        eventCentre: "যখন মাঝে",
        white: "সাদা",
        black: "কাল",
        sensorDistance: "সেন্সর থেকে দূরত্ব নাও",
        sensorObstacle:"বাধা সনাক্ত",
        sensorTrack: "সঠিক পথে",
        sensorLeft: "বামে সাদা",
        sensorRight: "ডানে সাদা",
        sensorCentre: "মাঝে সাদা",
        displayPoint: "বিন্দু আঁক",
        displayEllipseFill: "উপবৃত্তটি ভরাট করো",
        displayEllipse: "উপবৃত্ত আঁক",
        displayRectangleFill: "আয়তক্ষেত্রটি ভরাট করো",
        displayRectangle: "আয়তক্ষেত্র আঁক",
        displayLine:"সরলরেখা আঁক",
        from: "থেকে",
        to: "পর্যন্ত",
        displayClear: "সব মুছে ফেলো",
        displayText: "লেখা দেখাও",
        row: "সারি",
        col: "কলাম",
        wait: "অপেক্ষা করো",
        waitUntil: "অপেক্ষা করো যতক্ষণ না",
        ms: "মিলি সেকেন্ড",
        Task: "কাজ",
        thread: "একই সাথে করো",
        eventObstacle: "যখন সামনে বাধা পাবে"
    },

  httpRequestError: "There was a problem with the request.",
  linkAlert: "Share your blocks with this link:\n\n%1",
  hashError: "Sorry, '%1' doesn't correspond with any saved program.",
  xmlError: "Could not load your saved file. Perhaps it was created with a different version of Blockly?",
  badXml: "Error parsing XML:\n%1\n\nSelect 'OK' to abandon your changes or 'Cancel' to further edit the XML."
};
