var MSG = {
  title: "Visual Programming Editor",

  tab_blocks: "Blocks",
  tab_camera: "Feed",
  tab_code: "Code",

  aboutBtn:"About",
  exampleBtn:"Example",
  helpBtn:"Help",


  openTooltip: 'Open file',
  saveTooltip: 'Save workspace as file',
  linkTooltip: "Save and link to blocks.",
  runTooltip: "Run the program defined by the blocks in the workspace.",


  badCode: "Program error:\n%1",
  timeout: "Maximum execution iterations exceeded.",
  trashTooltip: "Discard all blocks.",

  catAction: "Action",
  catControl: "Control",
  catLogic: "Logic",
  catMath: "Math",
  catText: "Text",
  catLists: "Lists",
  catSensors: "Sensors",
  catEvents: "Events",
  catDisplay: "Display",
  catVariables: "Variables",
  catFunctions: "Functions",
  listVariable: "list",
  textVariable: "text",

    block : {
        goForwards: "go forwards",
        goBackwards: "go backwards",
        goSteps: "steps",
        stop: "stop",
        turnLeft: "turn left",
        turnRight: "turn right",
        eventVoice: "When voice input is",
        eventLeft: "When left is",
        eventRight: "When right is",
        eventCentre: "When centre is",
        white: "white",
        black: "black",
        sensorDistance: "get distance from sensor",
        sensorObstacle:"obstacle detected",
        sensorTrack: "on track",
        sensorLeft: "left is white",
        sensorRight: "right is white",
        sensorCentre: "centre is white",
        displayPoint: "draw point",
        displayEllipseFill: "fill the ellipse",
        displayEllipse: "draw ellipse",
        displayRectangleFill: "fill the rectangle",
        displayRectangle: "draw rectangle",
        displayLine:"draw a line",
        from: "from",
        to: "to",
        displayClear: "clear display",
        displayText: "show text",
        row: "in row",
        col: "in column",
        wait: "wait",
        waitUntil: "wait until",
        ms: "ms",
        Task: "Task",
        thread: "execute in parallel",
        eventObstacle: "When obstacle detected"
    },
  httpRequestError: "There was a problem with the request.",
  linkAlert: "Share your blocks with this link:\n\n%1",
  hashError: "Sorry, '%1' doesn't correspond with any saved program.",
  xmlError: "Could not load your saved file. Perhaps it was created with a different version of Blockly?",
  badXml: "Error parsing XML:\n%1\n\nSelect 'OK' to abandon your changes or 'Cancel' to further edit the XML."
};
